def generate_brief(
    project_name,
    agency,
    project_type,
    budget,
    location,
    score,
    risk_level
    
):
    # Priority Logic
    if score >= 80:
        priority = "High"

        recommendation = (
            "High-priority opportunity. Immediate review "
            "and stakeholder engagement recommended."
        )

    elif score >= 60:
        priority = "Medium"

        recommendation = (
            "Moderate opportunity. Further analysis "
            "recommended before action."
        )

    else:
        priority = "Low"

        recommendation = (
            "Low-priority opportunity. Monitor for "
            "future developments."
        )

    # Risk Insight
    if str(risk_level).lower() == "high":

        risk_comment = (
            "This opportunity carries significant "
            "execution or regulatory risks."
        )

    elif str(risk_level).lower() == "medium":

        risk_comment = (
            "This opportunity contains manageable "
            "risks that require monitoring."
        )

    else:

        risk_comment = (
            "This opportunity currently shows "
            "relatively low risk exposure."
        )
    if not location or str(location).strip() == "":
        location = "an unspecified location"
    
    if not budget or str(budget).strip() == "":
        budget = "Not Available"

    if location != "an unspecified location":
            summary = (
                f"This {project_type} initiative located in "
                f"{location} and managed by {agency} "
                f"has an estimated budget of {budget}. "
                f"The project has an opportunity score of "
                f"{score}, indicating "
            )
    
    else:

        summary = (
            f"This {project_type} initiative managed by "
            f"{agency} has an estimated budget of {budget}. "
            f"The project has an opportunity score of "
            f"{score}, indicating "
        )

    if score >= 80:
        summary += (
            "strong strategic potential and high "
            "business value."
        )

    elif score >= 60:
        summary += (
            "moderate potential that warrants "
            "further evaluation."
        )

    else:
        summary += (
            "limited potential and should be "
            "monitored carefully."
        )

    if score >= 80:
      impact = (
        "This project represents a high-value opportunity "
        "with strong potential for strategic partnerships "
        "and long-term revenue generation."
        )

    elif score >= 60:
      impact = (
        "This project offers moderate business potential "
        "and should be evaluated against current market priorities."
        )

    else:
      impact = (
        "This project should be monitored for future developments "
        "before significant resources are committed."
        )

    brief = f"""🧠 AI OPPORTUNITY BRIEF
==================================================

Project Name:
{project_name}

Agency:
{agency}

Opportunity Score:
{score}

Risk Level:
{risk_level}

Priority:
{priority}

--------------------------------------------------
EXECUTIVE SUMMARY
--------------------------------------------------

{summary}

--------------------------------------------------
BUSINESS IMPACT
--------------------------------------------------

{impact}       
--------------------------------------------------
RISK ANALYSIS
--------------------------------------------------

{risk_comment}

--------------------------------------------------
RECOMMENDED ACTION
--------------------------------------------------

{recommendation}

--------------------------------------------------
FINAL ASSESSMENT
--------------------------------------------------

Priority Level : {priority}
Opportunity Score : {score}
Risk Level : {risk_level}

Generated By:
AI-Powered Infrastructure Intelligence Platform
"""

    return brief